# Documentation at https://docs.docker.com/registry/deploying
version: '2'
services:
  registry:
    image: registry:2
    ports:
      - 443:5000
    restart: always  
    environment:
        # uncomment to enable basic auth
        #- REGISTRY_AUTH=htpasswd
        #- REGISTRY_AUTH_HTPASSWD_PATH=/auth/htpasswd
        #- REGISTRY_AUTH_HTPASSWD_REALM=Registry Realm

        # uncomment to enable tls with a certificate
        #- REGISTRY_HTTP_TLS_CERTIFICATE=/certs/domain.crt
        #- REGISTRY_HTTP_TLS_KEY=/certs/domain.key

        # uncomment to enable tls with letsencrypt
        - REGISTRY_HTTP_TLS_LETSENCRYPT_CACHEFILE=/letsencrypt/cachefile
        - REGISTRY_HTTP_TLS_LETSENCRYPT_EMAIL=yogendra.thakur@mindtree.com
    volumes:
        # uncomment to enable basic auth
        # you will need to generate a `htpasswd` file using :
        # docker run --entrypoint htpasswd registry:2 -Bbn admin admin > ~/volumes/registry/htpasswd
        #- ~/volumes/registry/htpasswd:/auth/htpasswd:ro

        # uncomment to enable tls
        #- /certs:/certs

        # uncomment to persist data to a volume
        - ~/volumes/registry/data:/var/lib/registry
        - /letsencrypt/cachefile:/letsencrypt/cachefile
  registry-ui:
    image: konradkleine/docker-registry-frontend:v2
    environment:
      - ENV_DOCKER_REGISTRY_HOST=registry
      - ENV_DOCKER_REGISTRY_PORT=5000
      - ENV_DOCKER_REGISTRY_USE_SSL=1
    ports:
      - 80:80

